trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: 'Build'
  jobs:
    - job: 'Build'
      steps:
      - task: UsePythonVersion@0
        displayName: "Setting python version to 3.6 as required by functions"
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
          
      - script: |
            rm trufflehog || true
            docker run gesellix/trufflehog --json https://github.com/medrim/riversafe-tech-poc > trufflehog
            cat trufflehog
        displayName: 'Scan repo'

      - bash: |
          if [ -f extensions.csproj ]
          then
              dotnet build extensions.csproj --output ./bin
          fi
          python3.6 -m venv worker_venv
          source worker_venv/bin/activate
          pip install --upgrade pip
          pip freeze > requirements.txt
          pip3.6 install setuptools
          pip3.6 install -r requirements.txt
    
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
              artifactName: 'drop'
              pathtoPublish: '$(System.DefaultWorkingDirectory)'
